HOST      = "localhost:8000" # change this to your domain
URL       = f"http://{HOST}" # change http to https
USERNAME  = "admin" # admin username
PASSWORD  = "111" # admin password
KEY       = "" # jwt secret key
ORIGINS   = [f"https://{HOST}", f"https://www.{HOST}"]
DOCS_URL  = "/docs" # swagger url
ALGORITHM = "HS256" # jwt algorithm
EXPIRY    = 24 # jwt expiry